language: ruby

rvm:
  - 2.1.0

# Don't include production only gems, such as unicorn (already present by default in Travis)
bundler_args: --without production

# Cache gems
cache: bundler

# Required to use new Travis container-based infrastructure
sudo: false

# Setup the database
before_script:
  - CODECLIMATE_REPO_TOKEN=26c7e954fe6e83150931914578222587ebd90734aca877d04a1a75d2d7823e2e
  - bundle exec rake db:create db:migrate
